version: '2'
services:
 phpcli:
   build:
     context: .
   working_dir: /var/www
   volumes:
    - .:/var/www

 db:
   image: mariadb
   #restart: always
   environment:
     MYSQL_ROOT_PASSWORD: secret
